INSERT INTO TBL_USER(FIRST_NAME, MIDDLE_NAME, LAST_NAME, USERNAME, EMAIL, PASSWORD) VALUES ('USER-01', 'M', 'L', 'user01',
'user01@user.com', 'dJ/Hy09vNJkLwMtnAUWx0Dyw7MwTFuyPvud9DvYOQ+M=');

INSERT INTO TBL_USER_GROUP(ID, GROUP_NAME) VALUES (1, 'GROUP 1');

INSERT INTO TBL_USER_LOG(ID, USER_ID) VALUES (1, 1);